modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="haileymod"
version="1.0.0"
displayName="HaileyMod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="hailey, MCreator"

[[dependencies.haileymod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




